### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Monsiz** [iDevMore/BuildLPs#1]
Hi, I see that there is no other way to get in contact with you but here.

Could you help me out setup the Netflix landing page? 

My discord is monsi#2066

**Comment by iDevMore** [comment]
Hello! Discord is telling me that you don't accept friend requests, so can't add you.

Anyways, you always can reach me on telegram: https://t.me/idev42

About the Netflix landing page. It's pretty outdated and seems that it's being hardly blocked, so not really useful at the moment. I have to make changes to it, but currently haven't time. :(
